# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-17 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Coffee_name', models.CharField(default=0, max_length=20)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
